radv: fix building error after 0833dd7d1
It seams that radv is the only driver using header <libdrm/drm_fourcc.h>
all others are using header <drm-uapi/drm_fourcc.h>

Fixes the following building error:

external/mesa/src/amd/vulkan/radv_image.c:28:10:
fatal error: 'libdrm/drm_fourcc.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Fixes: 0833dd7d1 ("amd/common: Add support for modifiers.")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>