android: gallium/aux: Add GPU tracepoint mechanism
Changelog:
- add util/u_tracepoints.{c,h} generated sources rules for Android
- update Makefile.sources with the required sources and generated sources

Fixes the following building error:

external/mesa/src/gallium/drivers/freedreno/freedreno_gmem.c:35:10:
fatal error: 'u_tracepoints.h' file not found
#include "u_tracepoints.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.

Fixes: 3471af9c6cfa ("gallium/aux: Add GPU tracepoint mechanism")