meson_options: Disable intel-rt by default
Commit 876db9135048 ("meson: rework intel-rt option to be a feature")
changed the default for `intel-rt` to enabled. Although, Meson detects
libclc, inte_clc does not, so the build is broken since Mesa 24.1.0.

    $ mkdir -p build && cd build && meson -Dbuildtype=release -Dgallium-drivers=iris,nouveau,r600,radeonsi,svga,swrast -Dgallium-opencl=icd -Dgallium-va=enabled -Dvulkan-drivers=amd,intel -Dosmesa=true -Dvalgrind=false -Dglvnd=true -Dprefix=/usr -Dlocalstatedir=/var -Dsysconfdir=/etc -Dwrap_mode=nofallback .. && ninja
    […]
    [2455/2724] env MESA_SHADER_CACHE_DISABLE=true MESA_SPIRV_LOG_LEVEL=error /dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/build/src/intel/compiler/intel_clc -p dg2 --prefix gfx125_bvh_postbuild_info_serialized_size -e serialized_size --in ../source/src/intel/vulkan/grl/gpu/bvh_postbuild_info.cl -o src/intel/vulkan/grl/gfx125_bvh_postbuild_info_serialized_size.h -- -cl-std=cl2.0 -D__OPENCL_VERSION__=200 -DMAX_HW_SIMD_WIDTH=16 -DMAX_WORKGROUP_SIZE=16 -I/dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/source/src/intel/vulkan/grl/gpu -I/dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/source/src/intel/vulkan/grl/include
    FAILED: src/intel/vulkan/grl/gfx125_bvh_postbuild_info_serialized_size.h
    env MESA_SHADER_CACHE_DISABLE=true MESA_SPIRV_LOG_LEVEL=error /dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/build/src/intel/compiler/intel_clc -p dg2 --prefix gfx125_bvh_postbuild_info_serialized_size -e serialized_size --in ../source/src/intel/vulkan/grl/gpu/bvh_postbuild_info.cl -o src/intel/vulkan/grl/gfx125_bvh_postbuild_info_serialized_size.h -- -cl-std=cl2.0 -D__OPENCL_VERSION__=200 -DMAX_HW_SIMD_WIDTH=16 -DMAX_WORKGROUP_SIZE=16 -I/dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/source/src/intel/vulkan/grl/gpu -I/dev/shm/bee-pmenzel/mesalib/mesalib-24.1.5-0/source/src/intel/vulkan/grl/include
    ERROR: libclc shader missing. Consider installing the libclc package
    […]

It can be worked around by explicitly disabling `intel-rt` with
`-D intel-rt=disabled`. Nevertheless, restore the behavior from before
the commit and default to disabled.

Fixes: 876db9135048 ("meson: rework intel-rt option to be a feature")
Closes: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11651
Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>