nir: fix intrinsic builders on MSVC C++
Fix this errors:
error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax

Signed-off-by: Rhys Perry <pendingchaos02@gmail.com>
Fixes: c9bcad25737 ("nir: add generated intrinsic builders")