nir/tests: require c++20 for designated initializers
This prevents a comiplation error on this form on MSVC:

../src/compiler/nir/tests/core_tests.cpp(83): error C7555: use of designated initializers requires at least '/std:c++20'