aco/meson: require c++20 for designated initializers
This prevents a comiplation error on this form on MSVC:

src/amd/compiler/aco_opcodes.cpp(33): error C7555: use of designated initializers requires at least '/std:c++20'