util/format: Check for NEON before using it
This fixes build on rpi0-w and any other machine which does not have
neon unit and is not used as FPU unit

Fixes errors e.g.

In file included from ../mesa-21.3.0/src/util/format/u_format_unpack_neon.c:35:
/mnt/b/yoe/master/build/tmp/work/arm1176jzfshf-vfp-yoe-linux-gnueabi/mesa/2_21.3.0-r0/recipe-sysroot-native/usr/lib/clang/13.0.1/include/arm_neon.h:32:2: error: "NEON support not enabled"

Signed-off-by: Khem Raj <raj.khem@gmail.com>