android: pan/bi: Generate bi_opcodes.{c,h}
Porting of commits 25c9946883ce and f9084b6c3f13 to Android makefile

Fixes the following building error:

In file included from external/mesa/src/panfrost/bifrost/bifrost_compile.c:36:
external/mesa/src/panfrost/bifrost/compiler.h:31:10: fatal error: 'bi_opcodes.h' file not found
         ^~~~~~~~~~~~~~
1 error generated.

Fixes: 25c9946883ce ("pan/bi: Generate bi_opcodes.c")
Fixes: f9084b6c3f13 ("pan/bi: Generate bi_opcodes.h")
Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>