aco/meson: require c++20 for designated initializers
Because Meson didn't add support for asking for C++20 directly until
Meson 0.60.0, we need to perform a version check and fall back to the
undocumented "c++latest" alternative.

This prevents this compilation error on MSVC:

src/amd/compiler/aco_opcodes.cpp(33): error C7555: use of designated initializers requires at least '/std:c++20'

Reviewed-by: Boris Brezillon <boris.brezillon@collabora.com>
Reviewed-by: Yonggang Luo <luoyonggang@gmail.com>