util: Fix SCons build.
  Compiling src/util/format/u_format_fxt1.c ...
src/util/format/u_format_fxt1.c:28:10: fatal error: util/format/u_format_pack.h: No such file or directory
   28 | #include "util/format/u_format_pack.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: a46b73ee250 ("mesa: Move the FXT1 compressor/decompressor to util/")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>