gitlab-ci: hold back meson on windows
If we update to Meson 0.58.1 on Windows, Meson's dependency scanning
starts crashing when scanning ACO in what looks like an encoding issue:

Here's an example of a failure:
https://gitlab.freedesktop.org/kusma/mesa/-/jobs/11095506#L368

---8<---
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\meson.exe\__main__.py", line 7, in <module>
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 231, in main
    return run(sys.argv[1:], launcher)
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 220, in run
    return run_script_command(args[1], args[2:])
  File "c:\python3\lib\site-packages\mesonbuild\mesonmain.py", line 168, in run_script_command
    return module.run(script_args)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 201, in run
    return scanner.scan()
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 152, in scan
    self.scan_file(s)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 53, in scan_file
    self.scan_cpp_file(fname)
  File "c:\python3\lib\site-packages\mesonbuild\scripts\depscan.py", line 111, in scan_cpp_file
    for line in fpath.read_text().split('\n'):
  File "c:\python3\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "c:\python3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 11367: character maps to <undefined>
---8<---

I've filed an upstream issue for this:
https://github.com/mesonbuild/meson/issues/8916

Until that has been resolved, let's lock down Meson to a known-working
version. I've chosen 0.57.2, because this is the latest version we have
evidence of working on CI.