android: amd/addrlib: define endianess to build
Fixes the following building error:

In file included from external/mesa/src/amd/addrlib/src/gfx9/gfx9addrlib.cpp:36:
external/mesa/src/amd/addrlib/src/chip/gfx9/gfx9_gb_reg.h:43:2: error: "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
 ^

NOTE: Android ABI specifies Little Endian for arm and x86 targets

Fixes: 3616e02ef3ee ("amd/addrlib: define endianess differently")