util/os_memory_fd: allow memfd_create from libc
FreeBSD >= 13.0 implements memfd_create() via SYS_shm_open2, so limit
__NR_memfd_create to Linux when not available in libc.

src/util/os_memory_fd.c:109:21: error: use of undeclared identifier '__NR_memfd_create'; did you mean 'memfd_create'?
   mem_fd = syscall(__NR_memfd_create, fd_name, MFD_CLOEXEC | MFD_ALLOW_SEALING);
                    ^~~~~~~~~~~~~~~~~
                    memfd_create
/usr/include/sys/mman.h:349:5: note: 'memfd_create' declared here
int     memfd_create(const char *, unsigned int);
        ^

Fixes: 1166ee9caf3e ("gallium: add utility and interface for memory fd allocations")
Reviewed-by: Eleni Maria Stea <elene.mst@gmail.com>
Reviewed-by: Jason Ekstrand <jason@jlekstrand.net>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13236>